# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Copy content of this repo to `blog`
      - name: Copy content
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /.
          src_branch: main
          dst_path: /content/
          dst_owner: simonlee2
          dst_repo_name: blog
          dst_branch: dev_simonlee
          exclude: '.github/**/*'
          clean: true
          commit_message: "chore(content): publish new content"
